services:
  db:
    image: postgres:17
    container_name: pg_campeonatos
    env_file: .env
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=${TZ}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: api_betano
    command: uvicorn app.main:app --host 0.0.0.0  --port 3000
    environment:
      - PYTHONUNBUFFERED=1
      - MAX_REQUESTS=1000
      - DISPLAY=:99
      - DATABASE_URL=postgresql://app_user:app_password@db:5432/campeonatos_db
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
    expose:
      - "3000"
    ports:
      - "3000:3000"
    volumes:
      - ./app/data:/api_betano/app/data  
      - .:/api_betano
    depends_on:
      - db

  nginx_api:
    image: nginx:latest
    container_name: nginx_proxy_api
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf 
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api

volumes:
  postgres_data: